import type { Metadata } from "next";
import StyledComponentsRegistry from "@/lib/regitstry";

export const metadata: Metadata = {
  title: "Jouer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
      </body>
    </html>
  );
}
